# Generated by Django 4.1 on 2022-10-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="UserInfo",),
    ]
